server:
  port: 8081

spring:
  application:
    name: consumer-api
  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 30000
    requested-heartbeat: 30
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0

fixed-income:
  queue:
    name: ${FIXED_INCOME_QUEUE_NAME:fixed-income.cdb.registry}
    exchange: ${FIXED_INCOME_EXCHANGE:fixed-income.direct}
    routing-key: ${FIXED_INCOME_ROUTING_KEY:cdb.registry.created}
    processing:
      batch-size: ${FIXED_INCOME_BATCH_SIZE:100}
      timeout: ${FIXED_INCOME_TIMEOUT:30000}
