server:
  port: 8080

spring:
  application:
    name: producer-api
  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 30000
    requested-heartbeat: 30

fixed-income:
  queue:
    name: ${FIXED_INCOME_QUEUE_NAME:fixed-income.cdb.registry}
    exchange: ${FIXED_INCOME_EXCHANGE:fixed-income.direct}
    routing-key: ${FIXED_INCOME_ROUTING_KEY:cdb.registry.created}